### ISSUE TITLE
Plugin not available

### ISSUE THREAD

**Issue by howowi** [oracle/oci-devops-jenkins-plugin#10]
Tried to find the plugin from Jenkins as stated in the readme but cannot find. Is it available for download yet?

https://plugins.jenkins.io/ui/search?sort=relevance&categories=&view=Tiles&page=1&query=Oracle%20Cloud%20Infrastructure%20DevOps%20Plugin

> Search for Oracle Cloud Infrastructure DevOps Plugin or oracle-cloud-infrastructure-devops.

**Comment by jyotisaini** [comment]
Hi @howowi  The OCI plugin for devops is not yet available in Jenkins marketplace. We are currently working on it. In the mean time, you can download the plugin from github release here. https://github.com/oracle/oci-devops-jenkins-plugin/releases/tag/v1.0.0
