### ISSUE TITLE
is the endpoint needed to call a DevOps deployment pipeline?

### ISSUE THREAD

**Issue by jonschreiber** [oracle/oci-devops-jenkins-plugin#9]
looking at the docs: https://github.com/oracle/oci-devops-jenkins-plugin/blob/main/README.md#usage-example-for-triggering-deployment

is the endpoint value needed for an OCIDeployment step?

**Comment by Soumya-UB** [comment]
Hi @jonschreiber sorry for the delayed response. Yes as per the current implementation, endpoint is a required parameter.

**Comment by jyotisaini** [comment]
Closing the issue. Feel free to reopen the issue if you need more clarification.
